# Generated by Django 3.0.5 on 2020-05-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='typeuser',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='FavoriteSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.User')),
                ('idserie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.User')),
                ('idmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Movie')),
            ],
        ),
    ]
